include_paths:
  - "/usr/local/include"
  - "/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include"
  - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
  - "/Library/Developer/CommandLineTools/usr/include"
  - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
sys_include_paths:
  - "/usr/local/include"
  - "/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include"
  - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
  - "/Library/Developer/CommandLineTools/usr/include"
  - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
predefine:
  - "#define __x86_64__ 1"