include_paths:
  - "/usr/local/include"
  - "/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include"
  - "/Users/YOURNAME/struct-bingen/exclude/c/header"
sys_include_paths:
  - "/usr/local/include"
  - "/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include"
  - "/Users/YOURNAME/struct-bingen/exclude/c/header"
predefine:
  - "#define __x86_64__ 1"